# Site settings
title: Harry's World
email: arrykrish@gmail.com
description: > 501, Lower Main Road, Millskock House, Obervatory, Cape Town, 7935
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Harry45.github.io" # the base hostname & protocol for your site
twitter_username: arrykrishna
github_username:  Harry45

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Student"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""